FikirsenWebSitesi_ASPNET_MVC/Controllers/YazilarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using FikirsenWebSitesi_ASPNET_MVC.Models;
using FikirsenWebSitesi_ASPNET_MVC.Models.entities;

namespace FikirsenWebSitesi_ASPNET_MVC.Controllers
{
    public class YazilarController : Controller
    {
        // GET: Yazilar
        FikirsenWebDBEntities3 db = new FikirsenWebDBEntities3();
        public ActionResult YaziListesi(int? sayfa)
        {
            int _sayfa = sayfa ?? 1;
            var degerler = db.Tbl_Yazilar.Where(x=> x.Tbl_Kullanicilar.KullaniciGirisAd == GirisKayit.girisAd).ToList().ToPagedList<Tbl_Yazilar>(_sayfa, 2);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YaziEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YaziEkle(Tbl_Yazilar p1)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.dgr = "Ekleme Başarısız !";
                return View("YaziEkle");
            }
            Tbl_Yazilar yeni = new Tbl_Yazilar();
            yeni.YaziBaslik = p1.YaziBaslik;
            yeni.YaziIcerik = p1.YaziIcerik;
            yeni.YazarID = GirisKayit.KullaniciID;
            db.Tbl_Yazilar.Add(yeni);
            db.SaveChanges();
            ViewBag.dgr = "Ekleme Başarılı";
            return View();
        }
        public ActionResult YaziGetir(int id)
        {
            var yazi = db.Tbl_Yazilar.Find(id);
            return View(yazi);
        }
        public ActionResult YaziGuncelle(Tbl_Yazilar p1)
        {
            var yazi = db.Tbl_Yazilar.Find(p1.YaziID);
            yazi.YaziIcerik = p1.YaziIcerik;
            yazi.YaziBaslik = p1.YaziBaslik;
            db.SaveChanges();
            return RedirectToAction("YaziListesi");
        }
        public ActionResult YaziSil(int id)
        {
            var yazi = db.Tbl_Yazilar.Find(id);
            db.Tbl_Yazilar.Remove(yazi);
            db.SaveChanges();
            return RedirectToAction("YaziListesi");
        }
    }
}

FikirsenWebSitesi_ASPNET_MVC/Views/Yazilar/YaziEkle.cshtml
@model FikirsenWebSitesi_ASPNET_MVC.Models.entities.Tbl_Yazilar

@{
    ViewBag.Title = "YaziEkle";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
          integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">
    <link href="~/Content/Main.css" type="text/css" rel="stylesheet" />

    <div class="container">
        <!-- LOGIN -->
        <form method="post" action="/Yazilar/YaziEkle" id="kayitForm1" class="anasayfa-all">
            <div class="form-group yaziEkleDiv">
                <span class="form-baslik yaziEkle-Anabaslik">Yazı Ekle</span>
                <span class="" id="yaziEkleDurumu">@ViewBag.dgr</span>
            </div>
            <div class="form-group yaziEkleDiv">
                <h4 class="yaziEkleBaslik">Başlık</h4>
                <input required type="text" class="form-control" placeholder="Başlık Giriniz" name="YaziBaslik" autofocus>
                @Html.ValidationMessageFor(m => m.YaziBaslik, "", new { @style = "color:red; font-weight:bold" })
            </div>
            <div class="form-group yaziEkleDiv">
                <h4 class="yaziEkleBaslik"><u>İçerik</u></h4>
                <textarea required class="form-control" placeholder="İçerik giriniz" name="YaziIcerik" autofocus style="height:200px"></textarea>
                @Html.ValidationMessageFor(m => m.YaziIcerik, "", new { @style = "color:red; font-weight:bold" })
            </div>
            <div class="form-group yaziEkleDiv">
                <button class="btn btn-block btn-success btn-uye" type="submit" id="btn1">Ekle</button>
            </div>
            <div class="form-group" style="font-size:18px; color:red; font-weight:bold; text-align:center;">
                @ViewBag.msg
            </div>
        </form>
    </div>
<script src="~/Content/KayitEkleJS.js"></script>

FikirsenWebSitesi_ASPNET_MVC/Views/Yazilar/YaziGetir.cshtml
@model FikirsenWebSitesi_ASPNET_MVC.Models.entities.Tbl_Yazilar
@{
    ViewBag.Title = "YaziGetir";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid anasayfa-all">
    @using (Html.BeginForm("YaziGuncelle", "Yazilar", FormMethod.Post))
    {
    <div class="form-group yaziEkleDiv">
        <label>Yazı ID</label>
        @Html.TextBoxFor(m => m.YaziID, new { @readonly = "readonly form", @class = "form-control" })
        <br />
        <label>Yazı İçerik</label>
        @Html.TextBoxFor(m => m.YaziBaslik, new { @class = "form-control" })
        <br />
        <label>Yazı İçerik</label>
        @Html.TextAreaFor(m => m.YaziIcerik, new { @class = "form-control", @rows = "15" })
        <br />
        <button class="btn btn-success">
            Güncelle
        </button>
    </div>
    }
</div>

FikirsenWebSitesi_ASPNET_MVC/Views/Yazilar/YaziListesi.cshtml
@using FikirsenWebSitesi_ASPNET_MVC.Models.entities
@using PagedList
@using PagedList.Mvc
@using FikirsenWebSitesi_ASPNET_MVC.Models

@model IPagedList<Tbl_Yazilar>

@{
    ViewBag.Title = "YaziListesi";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<link href="~/Content/Main.css" type="text/css" rel="stylesheet" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">

<div class="container-fluid anasayfa-all">
    <a href="/Yazilar/YaziEkle/" class="btn btn-primary btn-yazi-ekle">Yeni Yazı Ekle</a>
    @foreach (var yazi in Model)
    {
        <div class="anasayfa-mid">
            <div class="anasayfa-yazi">
                <h3 class="anasayfa-baslik">@yazi.YaziBaslik</h3>
                <p class="yazi-icerik">
                    @yazi.YaziIcerik
                </p>
                <br />
                <a href="/Yazilar/YaziGetir/@yazi.YaziID" class="btn-lg btn-success">GÜNCELLE</a>
                @Html.ActionLink("SİL", "YaziSil", new { id = yazi.YaziID }, new { @class = "btn-lg btn-warning", onclick = "return confirm('Silmek istediğinize emin misiniz?')" })
            </div>
        </div>
    }
    @Html.PagedListPager(Model, _sayfa => Url.Action("YaziListesi", "Yazilar", new { sayfa = _sayfa }))

</div>