FikirsenWebSitesi_ASPNET_MVC/Controllers/BilgiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FikirsenWebSitesi_ASPNET_MVC.Models;
using FikirsenWebSitesi_ASPNET_MVC.Models.entities;
namespace FikirsenWebSitesi_ASPNET_MVC.Controllers
{
    public class BilgiController : Controller
    {
        // GET: Sifre
        FikirsenWebDBEntities3 db = new FikirsenWebDBEntities3();
        [HttpGet]
        public ActionResult BilgiDegistir()
        {
            var degerler = db.Tbl_Kullanicilar.FirstOrDefault(x => x.KullaniciGirisAd == GirisKayit.girisAd.ToString());
            return View(degerler);
        }
        [HttpPost]
        public ActionResult BilgiDegistir(Tbl_Kullanicilar p1)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.dgr = "İşlem Başarısız !";
                return View("BilgiDegistir");
            }
            var degerler = db.Tbl_Kullanicilar.FirstOrDefault(x => x.KullaniciID == p1.KullaniciID);
            degerler.KullaniciAd = p1.KullaniciAd;
            degerler.KullaniciSoyad = p1.KullaniciSoyad;
            degerler.KullaniciMail = p1.KullaniciMail;
            degerler.KullaniciGirisAd = p1.KullaniciGirisAd;
            degerler.KullaniciGirisSifre = p1.KullaniciGirisSifre;
            db.SaveChanges();
            ViewBag.dgr = "İşlem Başarılı";
            return View();
        }

        
    }
}

FikirsenWebSitesi_ASPNET_MVC/Views/Bilgi/BilgiDegistir.cshtml
@using FikirsenWebSitesi_ASPNET_MVC.Models.entities
@model Tbl_Kullanicilar
@{
    ViewBag.Title = "SifreDegistir";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<link href="~/Content/Main.css" type="text/css" rel="stylesheet" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">

@using (Html.BeginForm("BilgiDegistir", "Bilgi", FormMethod.Post)) {
    <div class="container-fluid profil-all bilgiDegistirPage">
            <div class="profil-mid">
                <div class="profil-yazi bilgi-degistir-grid">
                    <h3 class="profil-baslik">Kişisel Bilgiler <span class="" id="yaziEkleDurumu">@ViewBag.dgr</span></h3>
                    <div>
                        <label class="profil-label">Kullanıcı ID : </label>
                            @Html.TextBoxFor(m => m.KullaniciID, new { @class = "form-control", @readonly = "readonly form" })
                    </div>
                    <div>
                        <label class="profil-label">Ad : </label>
                            @Html.TextBoxFor(m => m.KullaniciAd, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.KullaniciAd, "", new { @style = "color:red; font-weight:bold;" })
                    </div>
                    <div>
                        <label class="profil-label">Soyad : </label>
                            @Html.TextBoxFor(m => m.KullaniciSoyad, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.KullaniciSoyad, "", new { @style = "color:red; font-weight:bold;" })
                    </div>
                    <div>
                        <label class="profil-label">Mail : </label>
                            @Html.TextBoxFor(m => m.KullaniciMail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.KullaniciMail, "", new { @style = "color:red; font-weight:bold;" })
                    </div>
                    <div class="grid-gap">
                        <label class="profil-label">Kullanıcı Adı : </label>
                            @Html.TextBoxFor(m => m.KullaniciGirisAd, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.KullaniciGirisAd, "", new { @style = "color:red; font-weight:bold;" })
                    </div>
                    <div>
                        <label class="profil-label">Şifre : </label>
                            @Html.TextBoxFor(m => m.KullaniciGirisSifre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.KullaniciGirisSifre, "", new { @style = "color:red; font-weight:bold;" })
                    </div>
                    <button class="btn btn-lg btn-success btn-click">Değiştir</button>
                </div>
            </div>
    </div>
}
<script src="~/Content/KayitEkleJS.js"></script>